# SERVIDOR
server.port=8080

# BANCO H2 (em memória)
spring.datasource.url=jdbc:h2:mem:chamadosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / HIBERNATE

# create-drop: cria as tabelas ao iniciar e apaga ao encerrar
spring.jpa.hibernate.ddl-auto=create-drop

# Exibe o SQL gerado no console (útil para aprender e depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# CONSOLE WEB DO H2
# Acesse: http://localhost:8080/h2-console
# JDBC URL: jdbc:h2:mem:chamadosdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# SERIALIZAÇÃO DE ENUMS
# Faz o Jackson aceitar valores de Enum sem diferenciar maiúsculas/minúsculas
# Ex: "ti", "TI" e "Ti" são aceitos como SetorChamado.TI
spring.jackson.deserialization.fail-on-unknown-properties=false